/*
  curriculum/pre-a1.js — Pre-A1 foundation: reading direction, alphabet, greetings, numbers, essential vocabulary.
  Lesson fields: id, title, objective, pre (prerequisite lesson ids; default = previous lesson),
  concepts (taught here), practices (reviewed here), vocab (new words), notes (extra intro cards), exercises.
*/
(function (root) {
  const C = root.CURRICULUM = root.CURRICULUM || { vocabulary: [], concepts: [], units: [], lessons: [], conversations: [] };
  const unit = (id, title, icon, lessons) => C.units.push({ id, level: "pre-a1", title, icon, lessons });

  const LETTER_NAMES = { A: "אֵיי", B: "בִּי", C: "סִי", D: "דִּי", E: "אִי", F: "אֶף", G: "ג'ִי", H: "אֵייץ'", I: "אַיי", J: "ג'ֵיי", K: "קֵיי", L: "אֶל", M: "אֶם", N: "אֶן", O: "אוֹ", P: "פִּי", Q: "קְיוּ", R: "אַר", S: "אֶס", T: "טִי", U: "יוּ", V: "וִי", W: "דַּבֶּל-יוּ", X: "אֶקְס", Y: "וַאי", Z: "זִי" };
  const LETTER_WORDS = { A: "apple", B: "bag", C: "cat", D: "door", E: "egg", F: "fish", G: "girl", H: "house", I: "ink", J: "juice", K: "key", L: "lamp", M: "milk", N: "nine", O: "orange", P: "pen", Q: "queen", R: "red", S: "sun", T: "tea", U: "umbrella", V: "van", W: "water", X: "box", Y: "yes", Z: "zero" };
  // Spoken form of each letter name (bare single letters like "A" are ambiguous to TTS engines -> often read as "a" -> "uh").
  const LETTER_SPEECH = { A: "Ay", B: "Bee", C: "See", D: "Dee", E: "Ee", F: "Eff", G: "Jee", H: "Aitch", I: "Eye", J: "Jay", K: "Kay", L: "El", M: "Em", N: "En", O: "Oh", P: "Pee", Q: "Cue", R: "Ar", S: "Ess", T: "Tee", U: "You", V: "Vee", W: "Double-you", X: "Ex", Y: "Why", Z: "Zee" };
  const letterNote = (letters, title) => ({ title, body: "לכל אות: צורה גדולה, צורה קטנה, השם שלה ומילה לדוגמה. לחצי על 🔊 כדי לשמוע. (באות {X} המילה לדוגמה נגמרת ב-x: {box}.)",
    examples: letters.split("").map(L => [L + " " + L.toLowerCase() + " — " + LETTER_WORDS[L], LETTER_NAMES[L], LETTER_SPEECH[L] + ", " + LETTER_WORDS[L]]) });

  unit("pa-u1", "צעדים ראשונים", "🧭", [
    { id: "pa-intro", title: "איך קוראים אנגלית?", objective: "להבין שאנגלית נקראת משמאל לימין, ולהכיר אותיות גדולות וקטנות.",
      concepts: ["text-direction"], vocab: ["hello"],
      notes: [{ title: "ברוכה הבאה 👋", body: "אנחנו מתחילות מההתחלה ממש — וזה בדיוק המקום הנכון. בכל שיעור: קודם הסבר קצר, אחר כך דוגמאות עם שמע, ורק אז תרגול. טעויות הן חלק מהלמידה, ואין פה עונשים.", examples: [] }],
      exercises: [
        { mc: "באיזה כיוון קוראים אנגלית?", a: "משמאל לימין ➡️", o: ["מימין לשמאל ⬅️", "מלמעלה למטה ⬇️"], why: "באנגלית קוראים משמאל לימין — הפוך מעברית." },
        { mc: "המילה {Hello} מתחילה באות...", a: "H", o: ["o", "l"], why: "משמאל: {H} היא האות הראשונה." },
        { mc: "המילה {Dana} נגמרת באות...", a: "a", o: ["D", "n"], why: "הסוף הוא בצד ימין: {a}." },
        { mc: "איזו מילה מתחילה באות גדולה?", a: "Tom", o: ["tom", "tOM"], why: "אות גדולה רק בהתחלה: {Tom}." },
        { mc: "למה {Tel Aviv} מתחילה באות גדולה?", a: "כי זה שם של מקום", o: ["כי זו מילה ארוכה", "סתם, אין סיבה"], why: "שמות של אנשים ומקומות מתחילים באות גדולה." },
        { lis: "Hello", a: "Hello", o: ["Help", "Yellow"], why: "שמעת {Hello} — שלום." },
        { mc: "איזה משפט כתוב נכון?", a: "My name is Dana.", o: ["my name is dana.", "My Name Is Dana."], why: "אות גדולה בתחילת המשפט ובשם בלבד." },
        { mc: "כמה אותיות יש באלף-בית האנגלי?", a: "26", o: ["22", "30"], why: "באנגלית יש 26 אותיות (בעברית 22)." },
        { g: "say", v: "hello" },
      ] },
  ]);

  const abcExercises = {
    1: [
      { match: [["A", "a"], ["B", "b"], ["D", "d"], ["G", "g"]], why: "{A-a}, {B-b}, {D-d}, {G-g}." },
      { mc: "מה האות הקטנה של {B}?", a: "b", o: ["d", "p"], why: "{B} ← {b}: הבטן פונה ימינה." },
      { mc: "מה האות הגדולה של {d}?", a: "D", o: ["B", "P"], why: "{d} ← {D}." },
      { mc: "מה האות הקטנה של {F}?", a: "f", o: ["t", "e"], why: "{F} ← {f}." },
      { lis: "B", a: "B", o: ["D", "E"], why: "שמעת {B} — \"בִּי\"." },
      { lis: "F", a: "F", o: ["E", "G"], why: "שמעת {F} — \"אֶף\"." },
      { lis: "G", a: "G", o: ["C", "D"], why: "שמעת {G} — \"ג'ִי\"." },
      { mc: "באיזו אות מתחילה {apple} 🍎?", a: "A", o: ["E", "B"], why: "{apple} מתחילה ב-{A}." },
      { mc: "באיזו אות מתחילה {egg} 🥚?", a: "E", o: ["A", "G"], why: "{egg} מתחילה ב-{E}." },
      { mc: "מה בא אחרי {C}?", a: "D", o: ["B", "E"], why: "{A B C D E F G}." },
      { say: "A B C D E F G" },
    ],
    2: [
      { match: [["H", "h"], ["J", "j"], ["L", "l"], ["N", "n"]], why: "{H-h}, {J-j}, {L-l}, {N-n}." },
      { mc: "מה האות הקטנה של {M}?", a: "m", o: ["n", "w"], why: "{M} ← {m} (שתי גבעות)." },
      { mc: "מה האות הגדולה של {n}?", a: "N", o: ["M", "H"], why: "{n} ← {N}." },
      { mc: "מה האות הקטנה של {I}?", a: "i", o: ["l", "j"], why: "{I} ← {i} (עם נקודה)." },
      { lis: "H", a: "H", o: ["K", "A"], why: "שמעת {H} — \"אֵייץ'\"." },
      { lis: "J", a: "J", o: ["G", "K"], why: "שמעת {J} — \"ג'ֵיי\"." },
      { lis: "K", a: "K", o: ["Q", "H"], why: "שמעת {K} — \"קֵיי\"." },
      { mc: "באיזו אות מתחילה {milk} 🥛?", a: "M", o: ["N", "W"], why: "{milk} מתחילה בצליל \"מ\" = {M}." },
      { mc: "באיזו אות מתחילה {key} 🔑?", a: "K", o: ["C", "H"], why: "{key} מתחילה ב-{K}." },
      { mc: "באיזו אות מתחילה {lamp} 💡?", a: "L", o: ["I", "J"], why: "{lamp} מתחילה ב-{L}." },
      { mc: "באיזו אות מתחילה {house} 🏠?", a: "H", o: ["A", "O"], why: "{house} מתחילה ב-{H}." },
      { say: "H I J K L M N" },
    ],
    3: [
      { match: [["O", "o"], ["P", "p"], ["Q", "q"], ["R", "r"]], why: "{O-o}, {P-p}, {Q-q}, {R-r}." },
      { mc: "מה האות הקטנה של {P}?", a: "p", o: ["q", "b"], why: "{P} ← {p}." },
      { mc: "מה האות הקטנה של {Q}?", a: "q", o: ["p", "g"], why: "{Q} ← {q} (הזנב בצד ימין)." },
      { mc: "מה האות הגדולה של {u}?", a: "U", o: ["V", "N"], why: "{u} ← {U}." },
      { lis: "R", a: "R", o: ["A", "L"], why: "שמעת {R} — \"אַר\"." },
      { lis: "S", a: "S", o: ["F", "X"], why: "שמעת {S} — \"אֶס\"." },
      { lis: "T", a: "T", o: ["D", "P"], why: "שמעת {T} — \"טִי\"." },
      { mc: "באיזו אות מתחילה {pen} 🖊️?", a: "P", o: ["B", "F"], why: "{pen} מתחילה ב-{P}." },
      { mc: "באיזו אות מתחילה {tea} 🍵?", a: "T", o: ["D", "S"], why: "{tea} מתחילה ב-{T}." },
      { mc: "באיזו אות מתחילה {sun} ☀️?", a: "S", o: ["C", "Z"], why: "{sun} מתחילה ב-{S}." },
      { mc: "באיזו אות מתחילה {red} 🔴?", a: "R", o: ["L", "W"], why: "{red} מתחילה ב-{R}." },
      { say: "O P Q R S T U" },
    ],
    4: [
      { match: [["V", "v"], ["W", "w"], ["Y", "y"], ["Z", "z"]], why: "{V-v}, {W-w}, {Y-y}, {Z-z}." },
      { mc: "מה האות הקטנה של {W}?", a: "w", o: ["v", "m"], why: "{W} ← {w}." },
      { lis: "W", a: "W", o: ["V", "U"], why: "שמעת {W} — \"דַּבֶּל-יוּ\"." },
      { lis: "Y", a: "Y", o: ["I", "E"], why: "שמעת {Y} — \"וַאי\"." },
      { lis: "Z", a: "Z", o: ["C", "S"], why: "שמעת {Z} — \"זִי\"." },
      { mc: "איך מאייתים {cat}?", a: "C-A-T", o: ["K-A-T", "C-E-T"], why: "{cat} = {C-A-T}." },
      { mc: "איך מאייתים {yes}?", a: "Y-E-S", o: ["Y-A-S", "I-E-S"], why: "{yes} = {Y-E-S}." },
      { mc: "באיזו אות מתחילה {water} 💧?", a: "W", o: ["V", "U"], why: "{water} מתחילה ב-{W}." },
      { lt: "bag", why: "{bag} = {B-A-G}." },
      { lt: "pen", why: "{pen} = {P-E-N}." },
      { lt: "yes", why: "{yes} = {Y-E-S}." },
      { npc: "How do you spell your name?", a: "D-A-N-A.", o: ["Dana is fine.", "Yes, I am."], why: "על {How do you spell...?} עונים באותיות." },
      { say: "V W X Y Z" },
    ],
  };

  unit("pa-u2", "האלף-בית", "🔤", [
    { id: "pa-abc-1", title: "אותיות A עד G", objective: "לזהות את האותיות A–G בגדולות ובקטנות ולשמוע את שמן.", concepts: ["alphabet-letters"],
      notes: [letterNote("ABCDEFG", "האותיות A–G")], exercises: abcExercises[1] },
    { id: "pa-abc-2", title: "אותיות H עד N", objective: "לזהות את האותיות H–N ולהבין את ההבדל בין שם האות לצליל שלה.", concepts: ["letter-sounds"],
      notes: [letterNote("HIJKLMN", "האותיות H–N")], exercises: abcExercises[2] },
    { id: "pa-abc-3", title: "אותיות O עד U", objective: "לזהות את האותיות O–U ואת הצליל שבתחילת מילים פשוטות.", practices: ["alphabet-letters", "letter-sounds"],
      notes: [letterNote("OPQRSTU", "האותיות O–U")], exercises: abcExercises[3] },
    { id: "pa-abc-4", title: "אותיות V עד Z ואיות", objective: "להשלים את האלף-בית ולאיית מילים קצרות.", concepts: ["spelling"],
      notes: [letterNote("VWXYZ", "האותיות V–Z")], exercises: abcExercises[4] },
  ]);

  unit("pa-u3", "ברכות והיכרות", "👋", [
    { id: "pa-greet-1", title: "שלום ולהתראות", objective: "לברך ולהיפרד בזמנים שונים של היום.", pre: ["pa-abc-2"], concepts: ["greetings"],
      vocab: ["hello", "hi", "goodbye", "bye", "good-morning", "good-evening", "good-night", "see-you-later"],
      exercises: [
        { g: "en2he", v: ["hi", "goodbye", "good-morning", "good-night"] },
        { g: "listen", v: ["good-evening", "bye"] },
        { g: "match", v: ["hello", "goodbye", "good-morning", "good-night"] },
        { mc: "בשמונה בבוקר נכנסת למשרד. מה אומרים?", a: "Good morning!", o: ["Good night!", "Goodbye!"], why: "בבוקר: {Good morning}." },
        { mc: "הולכים לישון. מה אומרים?", a: "Good night!", o: ["Good evening!", "Hello!"], why: "{Good night} — רק כשנפרדים בלילה." },
        { g: "type", v: ["hello", "bye"] },
        { npc: "Hi! 👋", a: "Hello!", o: ["Goodbye!", "Good night!"], why: "על {Hi} עונים {Hello} או {Hi}." },
        { npc: "Bye! See you later.", a: "Bye!", o: ["Good morning!", "Hello!"], why: "כשמישהו נפרד עונים {Bye} / {Goodbye}." },
        { g: "say", v: ["good-morning"] },
      ] },
    { id: "pa-greet-2", title: "להציג את עצמי", objective: "להגיד איך קוראים לך, לשאול לשלום ולענות.", concepts: ["introductions"],
      vocab: ["my-name-is", "nice-to-meet-you", "how-are-you", "i-am-fine"], reviewVocab: ["hello", "hi"],
      exercises: [
        { g: "en2he", v: ["my-name-is", "nice-to-meet-you", "how-are-you"] },
        { g: "listen", v: ["i-am-fine"] },
        { fill: "My name ___ Dana.", a: "is", o: ["am", "are"], why: "תמיד {My name is}." },
        { build: "My name is Dana.", he: "קוראים לי דנה.", why: "{My name is} + שם." },
        { build: "Nice to meet you.", he: "נעים להכיר.", why: "הביטוי המלא: {Nice to meet you}." },
        { npc: "Hello! My name is Tom.", a: "Hi Tom! My name is Dana.", o: ["Good night, Tom.", "I am fine."], why: "כשמישהו מציג את עצמו — מציגים בחזרה." },
        { npc: "How are you?", a: "I am fine, thank you.", o: ["My name is Dana.", "Nice to meet you."], why: "על {How are you?} עונים איך מרגישים." },
        { tr: "קוראים לי דנה.", a: ["My name is Dana.", "I am Dana.", "I'm Dana."], why: "\"קוראים לי\" = {My name is}." },
        { lt: "Nice to meet you.", why: "שמעת: {Nice to meet you}." },
        { say: "My name is Dana.", a: ["My name is"], k: "אמרי בקול (אפשר עם השם שלך)" },
      ] },
    { id: "pa-greet-3", title: "תודה, בבקשה, סליחה", objective: "להשתמש במילות נימוס בסיסיות במצבים נכונים.", concepts: ["polite-words"],
      vocab: ["please", "thank-you", "sorry", "excuse-me", "yes", "no"],
      exercises: [
        { g: "emoji", v: ["yes", "no"] },
        { g: "en2he", v: ["please", "sorry", "excuse-me"] },
        { g: "listen", v: ["thank-you"] },
        { mc: "קיבלת קפה מהמלצר. מה אומרים?", a: "Thank you!", o: ["Sorry!", "Excuse me!"], why: "כשמקבלים משהו: {Thank you}." },
        { mc: "רוצה לעבור בין אנשים ברכבת. מה אומרים?", a: "Excuse me.", o: ["Thank you.", "Goodbye."], why: "{Excuse me} — כשרוצים לעבור או לפנות למישהו." },
        { fill: "Water, ___.", a: "please", o: ["sorry", "yes"], why: "כשמבקשים: {please}." },
        { npc: "Would you like some tea?", a: "Yes, please.", o: ["Yes, sorry.", "Excuse me, yes."], why: "כשמסכימים להצעה: {Yes, please}." },
        { npc: "Sorry, I am late.", a: "It's OK.", o: ["Thank you!", "Good morning!"], why: "על התנצלות עונים {It's OK} (זה בסדר)." },
        { g: "type", v: ["please", "sorry"] },
        { say: "Thank you very much!", a: ["thank you"] },
      ] },
  ]);

  unit("pa-u4", "מספרים", "🔢", [
    { id: "pa-num-1", title: "מספרים 0–10", objective: "לזהות, לשמוע ולכתוב את המספרים 0–10.", pre: ["pa-abc-2"], concepts: ["numbers-0-10"],
      vocab: ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"],
      exercises: [
        { g: "emoji", v: ["three", "seven", "ten"] },
        { g: "match", v: ["one", "two", "four", "five"] },
        { lis: "six", a: "6", o: ["7", "9"], why: "{six} = 6." },
        { lis: "eight", a: "8", o: ["3", "4"], why: "{eight} = 8." },
        { lis: "zero", a: "0", o: ["2", "10"], why: "{zero} = 0." },
        { mc: "{two} + {three} = ?", a: "five", o: ["four", "six"], why: "2+3=5 = {five}." },
        { mc: "{ten} − {one} = ?", a: "nine", o: ["eight", "seven"], why: "10−1=9 = {nine}." },
        { g: "type", v: ["four", "nine"] },
        { lt: "seven", a: ["7"], why: "{seven} = 7." },
        { say: "one, two, three, four, five", a: ["one two three four five"] },
      ] },
    { id: "pa-num-2", title: "מספרים 11–20", objective: "להבחין בין 13–19 ובין העשרות, ולכתוב אותם.", concepts: ["numbers-11-20"],
      vocab: ["eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty"],
      exercises: [
        { g: "match", v: ["eleven", "twelve", "fifteen", "twenty"] },
        { lis: "thirteen", a: "13", o: ["30", "3"], why: "{-teen} בסוף = 13–19. {thirteen} = 13." },
        { lis: "seventeen", a: "17", o: ["70", "7"], why: "{seventeen} = 17." },
        { lis: "twelve", a: "12", o: ["20", "2"], why: "{twelve} = 12." },
        { mc: "איך כותבים 18?", a: "eighteen", o: ["eightteen", "eighty"], why: "18 = {eighteen} (רק t אחת)." },
        { mc: "איך כותבים 15?", a: "fifteen", o: ["fiveteen", "fifty"], why: "15 = {fifteen}." },
        { mc: "{ten} + {ten} = ?", a: "twenty", o: ["twelve", "two"], why: "10+10=20 = {twenty}." },
        { g: "type", v: ["eleven", "twenty"] },
        { lt: "fourteen", a: ["14"], why: "{fourteen} = 14." },
        { lt: "nineteen", a: ["19"], why: "{nineteen} = 19." },
        { say: "thirteen, fourteen, fifteen", a: ["thirteen fourteen fifteen"] },
      ] },
    { id: "pa-num-3", title: "עשרות ומספרים עד 100", objective: "להבין ולומר מספרים עד 100: מחירים, גילים ושעות.", concepts: ["numbers-tens"],
      vocab: ["thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety", "one-hundred"],
      exercises: [
        { g: "match", v: ["thirty", "forty", "fifty", "one-hundred"] },
        { lis: "fifty", a: "50", o: ["15", "5"], why: "{fifty} = 50 (הדגש בהתחלה)." },
        { lis: "twenty-one", a: "21", o: ["12", "20"], why: "{twenty-one} = 21." },
        { lis: "sixty-five", a: "65", o: ["56", "16"], why: "{sixty-five} = 65: קודם העשרות." },
        { lis: "ninety-nine", a: "99", o: ["19", "90"], why: "{ninety-nine} = 99." },
        { mc: "איך כותבים 40?", a: "forty", o: ["fourty", "fourteen"], why: "40 = {forty} — בלי u." },
        { mc: "איך אומרים 34?", a: "thirty-four", o: ["four-thirty", "thirty and four"], why: "עשרות-יחידות: {thirty-four}." },
        { tre: "It is forty shekels.", a: "זה עולה 40 שקל.", o: ["זה עולה 14 שקל.", "זה עולה 4 שקל."], why: "{forty} = 40." },
        { g: "type", v: ["thirty", "eighty"] },
        { lt: "seventy-two", a: ["72"], why: "{seventy-two} = 72." },
        { say: "I am thirty years old.", a: ["I am thirty", "I'm thirty"] },
      ] },
  ]);

  unit("pa-u5", "מילים חיוניות", "🧺", [
    { id: "pa-people", title: "אנשים", objective: "להכיר מילים לאנשים סביבך.", pre: ["pa-greet-2"],
      vocab: ["man", "woman", "boy", "girl", "baby", "friend", "teacher", "student", "doctor", "person", "people"],
      exercises: [
        { g: "emoji", v: ["man", "woman", "boy", "girl", "baby"] },
        { g: "en2he", v: ["friend", "person", "people"] },
        { g: "he2en", v: ["teacher", "student"] },
        { g: "listen", v: ["teacher", "doctor"] },
        { g: "match", v: ["man", "woman", "friend", "student"] },
        { mc: "{woman} ← רבים?", a: "women", o: ["womans", "woman"], why: "{woman} ← {women}. תלמדי עוד על זה ב-A1." },
        { g: "type", v: ["friend", "student"] },
        { g: "say", v: ["teacher"] },
      ] },
    { id: "pa-family", title: "משפחה", objective: "לדבר על בני המשפחה.",
      vocab: ["mother", "father", "parents", "sister", "brother", "son", "daughter", "husband", "wife", "grandmother", "grandfather", "family", "children"],
      exercises: [
        { g: "emoji", v: ["grandmother", "grandfather", "family"] },
        { g: "en2he", v: ["parents", "son", "daughter", "husband", "wife"] },
        { g: "match", v: ["mother", "father", "sister", "brother"] },
        { g: "listen", v: ["children", "daughter"] },
        { tre: "My sister is a doctor.", a: "אחותי רופאה.", o: ["אחי רופא.", "אמא שלי רופאה."], why: "{sister} = אחות." },
        { g: "type", v: ["mother", "brother", "family"] },
        { lt: "My father is a teacher.", why: "{father} = אבא, {teacher} = מורה." },
        { g: "say", v: ["family"] },
      ] },
    { id: "pa-home", title: "בבית", objective: "לקרוא לחדרים ולרהיטים בבית בשמם.", pre: ["pa-greet-2"],
      vocab: ["house", "room", "kitchen", "bedroom", "bathroom", "door", "window", "table", "chair", "bed", "sofa"],
      exercises: [
        { g: "emoji", v: ["house", "door", "window", "chair", "sofa"] },
        { g: "en2he", v: ["kitchen", "bedroom", "bathroom"] },
        { g: "match", v: ["table", "bed", "room", "house"] },
        { g: "listen", v: ["kitchen", "window"] },
        { tre: "The kitchen is big.", a: "המטבח גדול.", o: ["חדר השינה גדול.", "המטבח קטן."], why: "{kitchen} = מטבח, {big} = גדול." },
        { g: "type", v: ["door", "table"] },
        { g: "say", v: ["bathroom"] },
      ] },
    { id: "pa-food", title: "אוכל", objective: "להכיר מאכלים יומיומיים.", pre: ["pa-greet-3"],
      vocab: ["bread", "egg", "cheese", "apple", "banana", "rice", "chicken", "fish", "salad", "soup", "cake", "sandwich", "tomato", "pizza"],
      exercises: [
        { g: "emoji", v: ["bread", "egg", "cheese", "banana", "fish", "cake"] },
        { g: "en2he", v: ["rice", "chicken", "soup"] },
        { g: "match", v: ["apple", "salad", "sandwich", "tomato"] },
        { g: "listen", v: ["chicken", "cheese"] },
        { npc: "What do you want?", a: "A sandwich, please.", o: ["A sandwich, sorry.", "Goodbye, sandwich."], why: "מבקשים ומוסיפים {please}." },
        { g: "type", v: ["bread", "apple", "egg"] },
        { g: "say", v: ["salad"] },
      ] },
    { id: "pa-drinks", title: "משקאות", objective: "להזמין ולהכיר משקאות.",
      vocab: ["water", "coffee", "tea", "milk", "juice", "wine"],
      exercises: [
        { g: "emoji", v: ["water", "coffee", "tea", "milk", "juice", "wine"] },
        { g: "listen", v: ["tea", "juice"] },
        { g: "he2en", v: ["milk", "wine"] },
        { g: "listenType", v: ["water"] },
        { g: "match", v: ["water", "coffee", "milk", "wine"] },
        { npc: "Coffee or tea?", a: "Tea, please.", o: ["Tea, sorry.", "Hello, tea."], why: "בוחרים ומוסיפים {please}." },
        { tre: "Coffee with milk, please.", a: "קפה עם חלב, בבקשה.", o: ["תה עם חלב, בבקשה.", "קפה בלי חלב, בבקשה."], why: "{coffee} = קפה, {milk} = חלב, {with} = עם." },
        { g: "type", v: ["water", "coffee", "milk"] },
        { g: "say", v: ["juice"] },
      ] },
    { id: "pa-objects", title: "חפצים", objective: "לקרוא בשם לחפצים שיש לנו ביד ובתיק.", pre: ["pa-greet-2"],
      vocab: ["phone", "book", "bag", "key", "pen", "cup", "computer", "watch", "glasses", "umbrella", "money"],
      exercises: [
        { g: "emoji", v: ["phone", "book", "key", "glasses", "umbrella", "money"] },
        { g: "en2he", v: ["bag", "cup", "watch"] },
        { g: "match", v: ["pen", "computer", "phone", "key"] },
        { g: "listen", v: ["umbrella", "computer"] },
        { g: "listenType", v: ["key", "book"] },
        { mc: "{Where is my key?} — מה מחפשים?", a: "מפתח 🔑", o: ["טלפון 📱", "תיק 👜"], why: "{key} = מפתח." },
        { g: "type", v: ["phone", "bag", "pen"] },
        { g: "say", v: ["glasses"] },
      ] },
    { id: "pa-places", title: "מקומות", objective: "להכיר מקומות בעיר.",
      vocab: ["home", "city", "street", "shop", "supermarket", "school", "work", "office", "hospital", "park", "restaurant", "bank", "beach"],
      exercises: [
        { g: "emoji", v: ["supermarket", "school", "hospital", "park", "bank", "beach"] },
        { g: "en2he", v: ["street", "city", "office"] },
        { g: "match", v: ["shop", "restaurant", "home", "work"] },
        { g: "listen", v: ["hospital", "restaurant"] },
        { mc: "{I am at home.} — איפה אני?", a: "בבית", o: ["בעבודה", "בבנק"], why: "{at home} = בבית." },
        { npc: "Excuse me, where is the bank?", a: "It's on this street.", o: ["Thank you, bank.", "Good night."], why: "שאלו איפה — עונים על מקום." },
        { g: "type", v: ["bank", "park", "shop"] },
        { g: "say", v: ["supermarket"] },
      ] },
    { id: "pa-colors", title: "צבעים", objective: "לומר צבעים ולשים אותם לפני שם העצם.", pre: ["pa-objects"], concepts: ["colors-before-nouns"],
      vocab: ["red", "blue", "green", "yellow", "black", "white", "orange", "purple", "brown", "pink", "gray"],
      exercises: [
        { g: "emoji", v: ["red", "blue", "green", "yellow", "black", "white"] },
        { g: "match", v: ["orange", "purple", "brown", "pink"] },
        { g: "listen", v: ["gray", "yellow"] },
        { mc: "איך אומרים \"תיק שחור\"?", a: "a black bag", o: ["a bag black", "black a bag"], why: "באנגלית הצבע לפני הדבר." },
        { fill: "I have a ___ car.", a: "red", o: ["reds"], why: "הצבע לא משתנה ולא מקבל s." },
        { build: "a white cup", he: "כוס לבנה", why: "צבע ואז הדבר: {a white cup}." },
        { build: "a green apple", he: "תפוח ירוק", why: "צבע ואז הדבר: {a green apple}." },
        { err: "I have a phone black.", a: "I have a black phone.", o: ["I have black a phone."], why: "הצבע לפני שם העצם." },
        { g: "type", v: ["blue", "white", "green"] },
        { g: "say", v: ["purple"] },
      ] },
    { id: "pa-actions", title: "פעולות בסיסיות", objective: "להגיד מה את עושה: אני אוכלת, אני עובדת...", pre: ["pa-food", "pa-places"], concepts: ["i-plus-verb"],
      vocab: ["eat", "drink", "go", "come", "sleep", "work-v", "read", "write", "speak", "listen", "see", "like", "want", "have", "live", "open", "close", "cook", "walk"],
      reviewVocab: ["bread", "coffee", "water", "home", "book"],
      exercises: [
        { g: "emoji", v: ["eat", "sleep", "write", "cook"] },
        { g: "en2he", v: ["go", "come", "see", "want", "live"] },
        { g: "match", v: ["open", "close", "read", "speak"] },
        { g: "listen", v: ["drink", "walk"] },
        { tre: "I drink coffee.", a: "אני שותה קפה.", o: ["אני אוכלת קפה.", "אני רוצה קפה."], why: "{drink} = לשתות." },
        { err: "I am eat bread.", a: "I eat bread.", o: ["I eating bread."], why: "{I} + פועל, בלי {am}." },
        { build: "I drink water.", he: "אני שותה מים.", why: "{I} + {drink} + {water}." },
        { build: "I live in Tel Aviv.", he: "אני גרה בתל אביב.", why: "{I live in} + מקום." },
        { build: "I like coffee.", he: "אני אוהבת קפה.", why: "{I} + {like} + {coffee}." },
        { tr: "אני קוראת ספר.", a: ["I read a book.", "I read books."], why: "{I read a book}." },
        { g: "type", v: ["eat", "sleep", "work-v"] },
        { say: "I speak Hebrew.", a: ["I speak hebrew"] },
      ] },
    { id: "pa-review", title: "סיכום Pre-A1", objective: "לחזור על כל היסודות לפני שעוברים ל-A1.",
      pre: ["pa-abc-4", "pa-num-3", "pa-family", "pa-home", "pa-drinks", "pa-colors", "pa-actions"],
      practices: ["introductions", "polite-words", "numbers-tens", "colors-before-nouns", "i-plus-verb"],
      reviewVocab: ["hello", "thank-you", "family", "kitchen", "coffee", "red", "eat", "friend", "bank"],
      exercises: [
        { npc: "Hi, I'm Anna. What's your name?", a: "My name is Dana. Nice to meet you.", o: ["I am fine, thank you.", "Goodbye, Anna."], why: "שאלו לשמך ← {My name is ...}.", c: "introductions" },
        { npc: "Coffee?", a: "Yes, please.", o: ["Yes, sorry.", "Excuse me."], why: "מסכימים להצעה: {Yes, please}.", c: "polite-words" },
        { lis: "forty-three", a: "43", o: ["34", "13"], why: "{forty-three} = 43.", c: "numbers-tens" },
        { lis: "eighteen", a: "18", o: ["80", "8"], why: "{eighteen} = 18.", c: "numbers-11-20" },
        { g: "emoji", v: ["family", "kitchen", "bank"] },
        { err: "I have a car red.", a: "I have a red car.", o: ["I have red a car."], why: "הצבע לפני הדבר.", c: "colors-before-nouns" },
        { build: "I eat bread and cheese.", he: "אני אוכלת לחם וגבינה.", why: "{I} + פועל + מה.", c: "i-plus-verb" },
        { tr: "אני אוהבת את המשפחה שלי.", a: ["I love my family.", "I like my family."], why: "{I love my family} — \"שלי\" = {my}, לפני הדבר.", c: "i-plus-verb" },
        { mc: "איך מאייתים {red}?", a: "R-E-D", o: ["R-A-D", "L-E-D"], why: "{red} = {R-E-D}.", c: "spelling" },
        { lt: "Good morning.", why: "{Good morning} = בוקר טוב.", c: "greetings" },
        { g: "type", v: ["friend", "coffee", "thank-you"] },
        { say: "Hello, my name is Dana. Nice to meet you.", a: ["hello my name is", "my name is"], c: "introductions" },
      ] },
  ]);
})(typeof globalThis !== "undefined" ? globalThis : this);
